security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'  

    # Fournisseur d'utilisateurs basé sur une entité User
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email 

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider  
            pattern: ^/
            custom_authenticators:
                - App\Security\AppAuthenticator  

            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email  
                password_parameter: password  
                always_use_default_target_path: true

            entry_point: form_login

            logout:
                path: app_logout
                target: app_home  
            remember_me:
                secret: '%kernel.secret%'  #A verifier avec ça si ça marche secret: '%env(APP_SECRET)%'
                lifetime: 604800 # 1 semaine
                path: /

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_EMPLOYE: [ROLE_USER]

    # Contrôle d'accès
    access_control:
       # - { path: ^/admin/service, roles: ROLE_EMPLOYE }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/veterinaire, roles: ROLE_VETERINAIRE }
        - { path: ^/employe, roles: ROLE_EMPLOYE }
        - { path: ^/login, roles: PUBLIC_ACCESS }  
        - { path: ^/logout, roles: IS_AUTHENTICATED_FULLY }
        

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 
                time_cost: 3 
                memory_cost: 10 
